name: CI/CD for chatGPT

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t chat-gpt-in-slack:latest

  # Deploy Job
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose down
          docker compose up -d